// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'online_classes';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String SPLASH1 = 'assets/gif/splash1.gif';
  static const String BG = 'assets/images/bg.png';
  static const String BG2 = 'assets/images/bg2.jpg';
  static const String CDS = 'assets/images/cds.png';
  static const String HANDS = 'assets/images/hands.jpg';
  static const String HSSC = 'assets/images/hssc.png';
  static const String IMG = 'assets/images/img.png';
  static const String IMG_1 = 'assets/images/img_1.png';
  static const String L1 = 'assets/images/l1.png';
  static const String L2 = 'assets/images/l2.png';
  static const String L3 = 'assets/images/l3.png';
  static const String L4 = 'assets/images/l4.png';
  static const String LOGO = 'assets/images/logo.jpeg';
  static const String NDA_2 = 'assets/images/nda 2.png';
  static const String NDA = 'assets/images/nda.png';
  static const String OTP = 'assets/images/otp.json';
  static const String S1 = 'assets/images/s1.png';
  static const String S2 = 'assets/images/s2.png';
  static const String S3 = 'assets/images/s3.png';
  static const String S4 = 'assets/images/s4.png';
  static const String S5 = 'assets/images/s5.png';
  static const String SPLASH = 'assets/images/splash.json';
  static const String SSC = 'assets/images/ssc.png';
  static const String STU = 'assets/images/stu.png';
  static const String UPSC = 'assets/images/upsc.png';
  static const String V1 = 'assets/images/v1.png';
  static const String V2 = 'assets/images/v2.png';
  static const String V3 = 'assets/images/v3.png';
  static const String V4 = 'assets/images/v4.png';
  static const String WELCOME = 'assets/images/welcome.json';
}
